### ISSUE TITLE
В коллекции детально, если нет ссылок сыпятся ошибки

### ISSUE THREAD

**Issue by redveronika** [Yamblz-Iceberg/iceberg-app#242]

**Comment by MoreBlood** [comment]
Баг был вызван ответом сервера с пустым объектом, пофикшен [костылем](https://github.com/Yamblz-Iceberg/iceberg-rest-api/commit/056675daac4ef92ca4b0769af14f3637c477dd4c#diff-825134276797e16ba6cfc3a32fe1d583R159)
